export const accountIcons = [
    // Money & Banking
    'wallet-outline',
    'cash-outline',
    'card-outline',
    'phone-portrait-outline',
    'business-outline',
    'briefcase-outline',
    'calculator-outline',
    'receipt-outline',
    'card-sharp',
    'wallet-sharp',
    'cellular-outline',
    'logo-paypal',
    'logo-bitcoin',
    'diamond-outline',
    'server-outline',
    'library-outline',

    // Savings & Investment
    'trending-up-outline',
    'analytics-outline',
    'bar-chart-outline',
    'pie-chart-outline',
    'stats-chart-outline',
    'podium-outline',
    'trophy-outline',
    'medal-outline',
    'ribbon-outline',
    'shield-checkmark-outline',

    // Property & Assets
    'home-outline',
    'business-outline',
    'car-outline',
    'bicycle-outline',
    'airplane-outline',
    'boat-outline',
    'train-outline',
    'bus-outline',
    'build-outline',
    'key-outline',

    // Lifestyle & Shopping
    'cart-outline',
    'bag-outline',
    'gift-outline',
    'basket-outline',
    'restaurant-outline',
    'fast-food-outline',
    'cafe-outline',
    'pizza-outline',
    'wine-outline',
    'beer-outline',

    // Health & Education
    'medical-outline',
    'fitness-outline',
    'school-outline',
    'book-outline',
    'library-outline',
    'newspaper-outline',
    'pencil-outline',
    'brush-outline',
    'bandage-outline',
    'pulse-outline',

    // Entertainment & Tech
    'game-controller-outline',
    'headset-outline',
    'desktop-outline',
    'laptop-outline',
    'phone-portrait-outline',
    'tablet-portrait-outline',
    'tv-outline',
    'musical-notes-outline',
    'film-outline',
    'camera-outline',

    // Utilities & Bills
    'bulb-outline',
    'flash-outline',
    'water-outline',
    'wifi-outline',
    'call-outline',
    'mail-outline',
    'cloud-outline',
    'flame-outline',
    'umbrella-outline',
    'toggle-outline',

    // Food & Groceries
    'nutrition-outline',
    'leaf-outline',
    'basket-outline',
    'fast-food-outline',
    'fish-outline',
    'egg-outline',
    'ice-cream-outline',
    'cafe-outline',
    'pizza-outline',
    'beer-outline',
    'water-outline',
    'cart-outline',

    // Household & Daily Life
    'shirt-outline',
    'cut-outline',
    'bed-outline',
    'today-outline',
    'storefront-outline',
    'sync-outline',
    'thermometer-outline',
    'timer-outline',
    'tissue-outline',
    'trash-outline',
    'download-outline',
    'extension-puzzle-outline',

    // Others
    'people-outline',
    'person-outline',
    'heart-outline',
    'paw-outline',
    'flower-outline',
    'leaf-outline',
    'telescope-outline',
    'planet-outline',
    'football-outline',
    'basketball-outline'
];
